version: '3.8'

networks:
  stinsons:
    driver: bridge

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - stinsons
  web:
    build: ./app
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - stinsons
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - nginx_data:/var/lib/nginx/data/
    networks:
      - stinsons

volumes:
  postgres_data:
  nginx_data:
