# Generated by Django 4.1 on 2023-11-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=1000),
        ),
    ]
